from app.models import db, User, Card, Comment
from faker import Faker
faker = Faker()

# Adds a demo user, you can add other users here if you want
def seed_cards():

    card_seeds = [
        {"api_id":89631146,"api_name":"Blue-Eyes White Dragon","api_set_name":"Legend of Blue Eyes White Dragon","api_set_code":"LOB-001","api_set_rarity":"Ultra Rare","api_set_price":"189.37"},
        {"api_id":76184692,"api_name":"Hitotsu-Me Giant","api_set_name":"Legend of Blue Eyes White Dragon","api_set_code":"LOB-002","api_set_rarity":"Common","api_set_price":"1.04"},
        {"api_id":45231178,"api_name":"Flame Swordsman","api_set_name":"Legend of Blue Eyes White Dragon","api_set_code":"LOB-003","api_set_rarity":"Super Rare","api_set_price":"7.35"},
        {"api_id":32274490,"api_name":"Skull Servant","api_set_name":"Legend of Blue Eyes White Dragon","api_set_code":"LOB-004","api_set_rarity":"Common","api_set_price":"2.88"},
        {"api_id":46986421,"api_name":"Dark Magician","api_set_name":"Legend of Blue Eyes White Dragon","api_set_code":"LOB-005","api_set_rarity":"Ultra Rare","api_set_price":"47.7"},
        {"api_id":6368039,"api_name":"Gaia The Fierce Knight","api_set_name":"Legend of Blue Eyes White Dragon","api_set_code":"LOB-006","api_set_rarity":"Ultra Rare","api_set_price":"11.92"},
        {"api_id":91152258,"api_name":"Celtic Guardian","api_set_name":"Legend of Blue Eyes White Dragon","api_set_code":"LOB-007","api_set_rarity":"Super Rare","api_set_price":"4.83"},
        {"api_id":89091579,"api_name":"Basic Insect","api_set_name":"Legend of Blue Eyes White Dragon","api_set_code":"LOB-008","api_set_rarity":"Common","api_set_price":"2.34"},
        {"api_id":40374923,"api_name":"Mammoth Graveyard","api_set_name":"Legend of Blue Eyes White Dragon","api_set_code":"LOB-009","api_set_rarity":"Common","api_set_price":"1.03"},
        {"api_id":90357090,"api_name":"Silver Fang","api_set_name":"Legend of Blue Eyes White Dragon","api_set_code":"LOB-010","api_set_rarity":"Common","api_set_price":"1.04"},
        {"api_id":9159938,"api_name":"Dark Gray","api_set_name":"Legend of Blue Eyes White Dragon","api_set_code":"LOB-011","api_set_rarity":"Common","api_set_price":"1.07"},
        {"api_id":77827521,"api_name":"Trial of Nightmare","api_set_name":"Legend of Blue Eyes White Dragon","api_set_code":"LOB-012","api_set_rarity":"Common","api_set_price":"1.02"},
        {"api_id":90963488,"api_name":"Nemuriko","api_set_name":"Legend of Blue Eyes White Dragon","api_set_code":"LOB-013","api_set_rarity":"Common","api_set_price":"1.04"},
        {"api_id":32864,"api_name":"The 13th Grave","api_set_name":"Legend of Blue Eyes White Dragon","api_set_code":"LOB-014","api_set_rarity":"Common","api_set_price":"2.24"},
        {"api_id":37421579,"api_name":"Charubin the Fire Knight","api_set_name":"Legend of Blue Eyes White Dragon","api_set_code":"LOB-015","api_set_rarity":"Rare","api_set_price":"1.17"},
        {"api_id":34460851,"api_name":"Flame Manipulator","api_set_name":"Legend of Blue Eyes White Dragon","api_set_code":"LOB-016","api_set_rarity":"Common","api_set_price":"1.01"},
        {"api_id":36121917,"api_name":"Monster Egg","api_set_name":"Legend of Blue Eyes White Dragon","api_set_code":"LOB-017","api_set_rarity":"Common","api_set_price":"1"},
        {"api_id":53293545,"api_name":"Firegrass","api_set_name":"Legend of Blue Eyes White Dragon","api_set_code":"LOB-018","api_set_rarity":"Common","api_set_price":"1.02"},
        {"api_id":17881964,"api_name":"Darkfire Dragon","api_set_name":"Legend of Blue Eyes White Dragon","api_set_code":"LOB-019","api_set_rarity":"Rare","api_set_price":"4.2"},
        {"api_id":53375573,"api_name":"Dark King of the Abyss","api_set_name":"Legend of Blue Eyes White Dragon","api_set_code":"LOB-020","api_set_rarity":"Common","api_set_price":"0.96"},
        {"api_id":2863439,"api_name":"Fiend Reflection #2","api_set_name":"Legend of Blue Eyes White Dragon","api_set_code":"LOB-021","api_set_rarity":"Common","api_set_price":"1.07"},
        {"api_id":1641882,"api_name":"Fusionist","api_set_name":"Legend of Blue Eyes White Dragon","api_set_code":"LOB-022","api_set_rarity":"Rare","api_set_price":"1.26"},
        {"api_id":37313348,"api_name":"Turtle Tiger","api_set_name":"Legend of Blue Eyes White Dragon","api_set_code":"LOB-023","api_set_rarity":"Common","api_set_price":"0.98"},
        {"api_id":75356564,"api_name":"Petit Dragon","api_set_name":"Legend of Blue Eyes White Dragon","api_set_code":"LOB-024","api_set_rarity":"Common","api_set_price":"1.22"},
        {"api_id":38142739,"api_name":"Petit Angel","api_set_name":"Legend of Blue Eyes White Dragon","api_set_code":"LOB-025","api_set_rarity":"Common","api_set_price":"1.5"},
        {"api_id":96851799,"api_name":"Hinotama Soul","api_set_name":"Legend of Blue Eyes White Dragon","api_set_code":"LOB-026","api_set_rarity":"Common","api_set_price":"1.04"},
        {"api_id":85639257,"api_name":"Aqua Madoor","api_set_name":"Legend of Blue Eyes White Dragon","api_set_code":"LOB-027","api_set_rarity":"Rare","api_set_price":"1.29"},
        {"api_id":15401633,"api_name":"Kagemusha of the Blue Flame","api_set_name":"Legend of Blue Eyes White Dragon","api_set_code":"LOB-028","api_set_rarity":"Common","api_set_price":"1.06"},
        {"api_id":58528964,"api_name":"Flame Ghost","api_set_name":"Legend of Blue Eyes White Dragon","api_set_code":"LOB-029","api_set_rarity":"Rare","api_set_price":"2.23"},
        {"api_id":73134082,"api_name":"Final Flame","api_set_name":"Legend of Blue Eyes White Dragon","api_set_code":"LOB-100","api_set_rarity":"Rare","api_set_price":"1.49"},
        {"api_id":72302403,"api_name":"Swords of Revealing Light","api_set_name":"Legend of Blue Eyes White Dragon","api_set_code":"LOB-101","api_set_rarity":"Super Rare","api_set_price":"3.05"},
        {"api_id":11868825,"api_name":"Goblin's Secret Remedy","api_set_name":"Legend of Blue Eyes White Dragon","api_set_code":"LOB-099","api_set_rarity":"Rare","api_set_price":"1.14"},
        {"api_id":9293977,"api_name":"Metal Dragon","api_set_name":"Legend of Blue Eyes White Dragon","api_set_code":"LOB-102","api_set_rarity":"Rare","api_set_price":"1.62"},
        {"api_id":63102017,"api_name":"Stop Defense","api_set_name":"Legend of Blue Eyes White Dragon","api_set_code":"LOB-095","api_set_rarity":"Rare","api_set_price":"1.9"},
        {"api_id":37820550,"api_name":"Electro-Whip","api_set_name":"Legend of Blue Eyes White Dragon","api_set_code":"LOB-093","api_set_rarity":"Common","api_set_price":"0.98"},
        {"api_id":93553943,"api_name":"Man Eater","api_set_name":"Legend of Blue Eyes White Dragon","api_set_code":"LOB-075","api_set_rarity":"Common","api_set_price":"0.99"},
        {"api_id":38199696,"api_name":"Red Medicine","api_set_name":"Legend of Blue Eyes White Dragon","api_set_code":"LOB-054","api_set_rarity":"Common","api_set_price":"1.08"},
        {"api_id":7089711,"api_name":"Hane-Hane","api_set_name":"Legend of Blue Eyes White Dragon","api_set_code":"LOB-110","api_set_rarity":"Rare","api_set_price":"1.39"},
        {"api_id":12580477,"api_name":"Raigeki","api_set_name":"Legend of Blue Eyes White Dragon","api_set_code":"LOB-053","api_set_rarity":"Super Rare","api_set_price":"6.04"},
        {"api_id":53129443,"api_name":"Dark Hole","api_set_name":"Legend of Blue Eyes White Dragon","api_set_code":"LOB-052","api_set_rarity":"Super Rare","api_set_price":"5.75"},
        {"api_id":22702055,"api_name":"Umi","api_set_name":"Legend of Blue Eyes White Dragon","api_set_code":"LOB-050","api_set_rarity":"Common","api_set_price":"2.35"},
        {"api_id":33178416,"api_name":"Misairuzame","api_set_name":"Legend of Blue Eyes White Dragon","api_set_code":"LOB-111","api_set_rarity":"Common","api_set_price":"1.02"},
        {"api_id":29172562,"api_name":"Steel Ogre Grotto #1","api_set_name":"Legend of Blue Eyes White Dragon","api_set_code":"LOB-112","api_set_rarity":"Common","api_set_price":"1.03"},
        {"api_id":66889139,"api_name":"Gaia the Dragon Champion","api_set_name":"Legend of Blue Eyes White Dragon","api_set_code":"LOB-125","api_set_rarity":"Secret Rare","api_set_price":"9.74"},
        {"api_id":33396948,"api_name":"Exodia the Forbidden One","api_set_name":"Legend of Blue Eyes White Dragon","api_set_code":"LOB-124","api_set_rarity":"Ultra Rare","api_set_price":"43.44"},
        {"api_id":7902349,"api_name":"Left Arm of the Forbidden One","api_set_name":"Legend of Blue Eyes White Dragon","api_set_code":"LOB-123","api_set_rarity":"Ultra Rare","api_set_price":"15.5"},
        {"api_id":70903634,"api_name":"Right Arm of the Forbidden One","api_set_name":"Legend of Blue Eyes White Dragon","api_set_code":"LOB-122","api_set_rarity":"Ultra Rare","api_set_price":"17.65"},
        {"api_id":44519536,"api_name":"Left Leg of the Forbidden One","api_set_name":"Legend of Blue Eyes White Dragon","api_set_code":"LOB-121","api_set_rarity":"Ultra Rare","api_set_price":"14.26"},
        {"api_id":8124921,"api_name":"Right Leg of the Forbidden One","api_set_name":"Legend of Blue Eyes White Dragon","api_set_code":"LOB-120","api_set_rarity":"Ultra Rare","api_set_price":"17.99"},
        {"api_id":83764719,"api_name":"Monster Reborn","api_set_name":"Legend of Blue Eyes White Dragon","api_set_code":"LOB-118","api_set_rarity":"Ultra Rare","api_set_price":"16.49"},
        {"api_id":55144522,"api_name":"Pot of Greed","api_set_name":"Legend of Blue Eyes White Dragon","api_set_code":"LOB-119","api_set_rarity":"Rare","api_set_price":"4.89"},
        {"api_id":48094997,"api_name":"Battle Footballer","api_set_name":"Dark Crisis","api_set_code":"DCR-001","api_set_rarity":"Common","api_set_price":"1.1"},
        {"api_id":11987744,"api_name":"Nin-Ken Dog","api_set_name":"Dark Crisis","api_set_code":"DCR-002","api_set_rarity":"Common","api_set_price":"0.95"},
        {"api_id":47372349,"api_name":"Acrobat Monkey","api_set_name":"Dark Crisis","api_set_code":"DCR-003","api_set_rarity":"Common","api_set_price":"1.01"},
        {"api_id":85489096,"api_name":"Arsenal Summoner","api_set_name":"Dark Crisis","api_set_code":"DCR-004","api_set_rarity":"Common","api_set_price":"3.19"},
        {"api_id":74367458,"api_name":"Guardian Elma","api_set_name":"Dark Crisis","api_set_code":"DCR-005","api_set_rarity":"Common","api_set_price":"1.09"},
        {"api_id":10755153,"api_name":"Guardian Ceal","api_set_name":"Dark Crisis","api_set_code":"DCR-006","api_set_rarity":"Ultra Rare","api_set_price":"4.7"},
        {"api_id":47150851,"api_name":"Guardian Grarl","api_set_name":"Dark Crisis","api_set_code":"DCR-007","api_set_rarity":"Ultra Rare","api_set_price":"6.49"},
        {"api_id":73544866,"api_name":"Guardian Baou","api_set_name":"Dark Crisis","api_set_code":"DCR-008","api_set_rarity":"Rare","api_set_price":"1.09"},
        {"api_id":9633505,"api_name":"Guardian Kay'est","api_set_name":"Dark Crisis","api_set_code":"DCR-009","api_set_rarity":"Common","api_set_price":"1.13"},
        {"api_id":46037213,"api_name":"Guardian Tryce","api_set_name":"Dark Crisis","api_set_code":"DCR-010","api_set_rarity":"Rare","api_set_price":"1.07"},
        {"api_id":2851070,"api_name":"Reflect Bounder","api_set_name":"Dark Crisis","api_set_code":"DCR-012","api_set_rarity":"Ultra Rare","api_set_price":"11.17"},
        {"api_id":81985784,"api_name":"Des Feral Imp","api_set_name":"Dark Crisis","api_set_code":"DCR-014","api_set_rarity":"Rare","api_set_price":"2.57"},
        {"api_id":50939127,"api_name":"Different Dimension Dragon","api_set_name":"Dark Crisis","api_set_code":"DCR-015","api_set_rarity":"Super Rare","api_set_price":"4.25"},
        {"api_id":86327225,"api_name":"Shinato, King of a Higher Plane","api_set_name":"Dark Crisis","api_set_code":"DCR-016","api_set_rarity":"Ultra Rare","api_set_price":"11.17"},
        {"api_id":13722870,"api_name":"Dark Flare Knight","api_set_name":"Dark Crisis","api_set_code":"DCR-017","api_set_rarity":"Super Rare","api_set_price":"6.8"},
        {"api_id":49217579,"api_name":"Mirage Knight","api_set_name":"Dark Crisis","api_set_code":"DCR-018","api_set_rarity":"Super Rare","api_set_price":"6.29"},
        {"api_id":85605684,"api_name":"Berserk Dragon","api_set_name":"Dark Crisis","api_set_code":"DCR-019","api_set_rarity":"Super Rare","api_set_price":"5.65"},
        {"api_id":12600382,"api_name":"Exodia Necross","api_set_name":"Dark Crisis","api_set_code":"DCR-020","api_set_rarity":"Ultra Rare","api_set_price":"28.99"},
        {"api_id":9817927,"api_name":"Gyaku-Gire Panda","api_set_name":"Dark Crisis","api_set_code":"DCR-021","api_set_rarity":"Common","api_set_price":"6.14"},
        {"api_id":35215622,"api_name":"Blindly Loyal Goblin","api_set_name":"Dark Crisis","api_set_code":"DCR-022","api_set_rarity":"Common","api_set_price":"1.1"},
        {"api_id":28106077,"api_name":"Cestus of Dagla","api_set_name":"Dark Crisis","api_set_code":"DCR-090","api_set_rarity":"Common","api_set_price":"1.06"},
        {"api_id":56246017,"api_name":"Archfiend's Roar","api_set_name":"Dark Crisis","api_set_code":"DCR-099","api_set_rarity":"Common","api_set_price":"1.01"},
        {"api_id":20858318,"api_name":"Dark Scorpion Combination","api_set_name":"Dark Crisis","api_set_code":"DCR-098","api_set_rarity":"Rare","api_set_price":"1.01"},
        {"api_id":20188127,"api_name":"Fairy of the Spring","api_set_name":"Dark Crisis","api_set_code":"DCR-040","api_set_rarity":"Common","api_set_price":"0.98"},
        {"api_id":42941100,"api_name":"Ojama Yellow","api_set_name":"Invasion of Chaos","api_set_code":"IOC-001","api_set_rarity":"Common","api_set_price":"1.36"},
        {"api_id":79335209,"api_name":"Ojama Black","api_set_name":"Invasion of Chaos","api_set_code":"IOC-002","api_set_rarity":"Common","api_set_price":"1.24"},
        {"api_id":42129512,"api_name":"Big Koala","api_set_name":"Invasion of Chaos","api_set_code":"IOC-004","api_set_rarity":"Common","api_set_price":"1.06"},
        {"api_id":78613627,"api_name":"Des Kangaroo","api_set_name":"Invasion of Chaos","api_set_code":"IOC-005","api_set_rarity":"Common","api_set_price":"1.03"},
        {"api_id":14618326,"api_name":"Crimson Ninja","api_set_name":"Invasion of Chaos","api_set_code":"IOC-006","api_set_rarity":"Common","api_set_price":"1.03"},
        {"api_id":41006930,"api_name":"Strike Ninja","api_set_name":"Invasion of Chaos","api_set_code":"IOC-007","api_set_rarity":"Ultra Rare","api_set_price":"5.47"},
        {"api_id":69542930,"api_name":"Dedication through Light and Darkness","api_set_name":"Invasion of Chaos","api_set_code":"IOC-095","api_set_rarity":"Super Rare","api_set_price":"1.72"},
        {"api_id":23557835,"api_name":"Dimension Fusion","api_set_name":"Invasion of Chaos","api_set_code":"IOC-094","api_set_rarity":"Ultra Rare","api_set_price":"61.13"},
        {"api_id":77491079,"api_name":"Gale Lizard","api_set_name":"Invasion of Chaos","api_set_code":"IOC-008","api_set_rarity":"Common","api_set_price":"1.08"},
        {"api_id":37957847,"api_name":"Insect Princess","api_set_name":"Invasion of Chaos","api_set_code":"IOC-080","api_set_rarity":"Ultra Rare","api_set_price":"5.17"},
        {"api_id":3773196,"api_name":"D.D. Scout Plane","api_set_name":"Invasion of Chaos","api_set_code":"IOC-012","api_set_rarity":"Super Rare","api_set_price":"2.48"},
        {"api_id":38670435,"api_name":"Black Tyranno","api_set_name":"Invasion of Chaos","api_set_code":"IOC-075","api_set_rarity":"Ultra Rare","api_set_price":"7.2"},
        {"api_id":42541548,"api_name":"Coach Goblin","api_set_name":"Invasion of Chaos","api_set_code":"IOC-015","api_set_rarity":"Common","api_set_price":"0.95"},
        {"api_id":218704,"api_name":"Fenrir","api_set_name":"Invasion of Chaos","api_set_code":"IOC-020","api_set_rarity":"Common","api_set_price":"1.55"},
        {"api_id":94192409,"api_name":"Compulsory Evacuation Device","api_set_name":"Invasion of Chaos","api_set_code":"IOC-103","api_set_rarity":"Rare","api_set_price":"1.67"},
        {"api_id":47606319,"api_name":"Gigantes","api_set_name":"Invasion of Chaos","api_set_code":"IOC-021","api_set_rarity":"Common","api_set_price":"2.44"},
        {"api_id":73001017,"api_name":"Silpheed","api_set_name":"Invasion of Chaos","api_set_code":"IOC-022","api_set_rarity":"Common","api_set_price":"0.96"},
        {"api_id":9596126,"api_name":"Chaos Sorcerer","api_set_name":"Invasion of Chaos","api_set_code":"IOC-023","api_set_rarity":"Common","api_set_price":"1.29"},
        {"api_id":36584821,"api_name":"Gren Maju Da Eiza","api_set_name":"Invasion of Chaos","api_set_code":"IOC-024","api_set_rarity":"Common","api_set_price":"2.05"},
        {"api_id":72989439,"api_name":"Black Luster Soldier - Envoy of the Beginning","api_set_name":"Invasion of Chaos","api_set_code":"IOC-025","api_set_rarity":"Ultra Rare","api_set_price":"37.59"},
        {"api_id":8251996,"api_name":"Ojama Delta Hurricane!!","api_set_name":"Invasion of Chaos","api_set_code":"IOC-034","api_set_rarity":"Short Print","api_set_price":"1.67"},
        {"api_id":40737112,"api_name":"Dark Magician of Chaos","api_set_name":"Invasion of Chaos","api_set_code":"IOC-065","api_set_rarity":"Ultra Rare","api_set_price":"27.65"},
        {"api_id":82301904,"api_name":"Chaos Emperor Dragon - Envoy of the End","api_set_name":"Invasion of Chaos","api_set_code":"IOC-000","api_set_rarity":"Secret Rare","api_set_price":"53.9"},
        {"api_id":69140099,"api_name":"Gemini Elf","api_set_name":"Labyrinth of Nightmare","api_set_code":"LON-000","api_set_rarity":"Secret Rare","api_set_price":"24.8"},
        {"api_id":62279055,"api_name":"Magic Cylinder","api_set_name":"Labyrinth of Nightmare","api_set_code":"LON-104","api_set_rarity":"Secret Rare","api_set_price":"12.44"},
        {"api_id":49064413,"api_name":"The Masked Beast","api_set_name":"Labyrinth of Nightmare","api_set_code":"LON-001","api_set_rarity":"Ultra Rare","api_set_price":"9.39"},
        {"api_id":95220856,"api_name":"Vengeful Bog Spirit","api_set_name":"Labyrinth of Nightmare","api_set_code":"LON-103","api_set_rarity":"Short Print","api_set_price":"1.74"},
        {"api_id":3573512,"api_name":"Swordsman of Landstar","api_set_name":"Labyrinth of Nightmare","api_set_code":"LON-002","api_set_rarity":"Common","api_set_price":"1.05"},
        {"api_id":73216412,"api_name":"Worm Drake","api_set_name":"Labyrinth of Nightmare","api_set_code":"LON-004","api_set_rarity":"Common","api_set_price":"0.97"},
        {"api_id":69832741,"api_name":"Spirit Elimination","api_set_name":"Labyrinth of Nightmare","api_set_code":"LON-102","api_set_rarity":"Common","api_set_price":"0.97"},
        {"api_id":5600127,"api_name":"Humanoapi_id Worm Drake","api_set_name":"Labyrinth of Nightmare","api_set_code":"LON-005","api_set_rarity":"Short Print","api_set_price":"3.14"},
        {"api_id":32437102,"api_name":"Dragonic Attack","api_set_name":"Labyrinth of Nightmare","api_set_code":"LON-101","api_set_rarity":"Common","api_set_price":"0.99"},
        {"api_id":31709826,"api_name":"Revival Jam","api_set_name":"Labyrinth of Nightmare","api_set_code":"LON-006","api_set_rarity":"Super Rare","api_set_price":"4.69"},
        {"api_id":31987274,"api_name":"Flying Fish","api_set_name":"Labyrinth of Nightmare","api_set_code":"LON-007","api_set_rarity":"Common","api_set_price":"0.96"},
        {"api_id":67371383,"api_name":"Amphibian Beast","api_set_name":"Labyrinth of Nightmare","api_set_code":"LON-008","api_set_rarity":"Rare","api_set_price":"1.14"},
        {"api_id":6343408,"api_name":"Miracle Dig","api_set_name":"Labyrinth of Nightmare","api_set_code":"LON-100","api_set_rarity":"Common","api_set_price":"0.99"},
        {"api_id":3078576,"api_name":"Yata-Garasu","api_set_name":"Legacy of Darkness","api_set_code":"LOD-000","api_set_rarity":"Secret Rare","api_set_price":"71.85"},
        {"api_id":79575620,"api_name":"Injection Fairy Lily","api_set_name":"Legacy of Darkness","api_set_code":"LOD-100","api_set_rarity":"Secret Rare","api_set_price":"23.65"},
        {"api_id":53982768,"api_name":"Dark Ruler Ha Des","api_set_name":"Legacy of Darkness","api_set_code":"LOD-001","api_set_rarity":"Ultra Rare","api_set_price":"4.29"},
        {"api_id":80071763,"api_name":"Dark Balter the Terrible","api_set_name":"Legacy of Darkness","api_set_code":"LOD-002","api_set_rarity":"Super Rare","api_set_price":"10.36"},
        {"api_id":16475472,"api_name":"Lesser Fiend","api_set_name":"Legacy of Darkness","api_set_code":"LOD-003","api_set_rarity":"Rare","api_set_price":"1.04"},
        {"api_id":52860176,"api_name":"Possessed Dark Soul","api_set_name":"Legacy of Darkness","api_set_code":"LOD-004","api_set_rarity":"Common","api_set_price":"1.06"},
        {"api_id":89258225,"api_name":"Winged Minion","api_set_name":"Legacy of Darkness","api_set_code":"LOD-005","api_set_rarity":"Common","api_set_price":"1"},
        {"api_id":28566710,"api_name":"Last Turn","api_set_name":"Legacy of Darkness","api_set_code":"LOD-099","api_set_rarity":"Ultra Rare","api_set_price":"10.43"},
        {"api_id":81172177,"api_name":"Fiend Comedian","api_set_name":"Legacy of Darkness","api_set_code":"LOD-098","api_set_rarity":"Common","api_set_price":"1.37"},
        {"api_id":15653824,"api_name":"Skull Knight #2","api_set_name":"Legacy of Darkness","api_set_code":"LOD-006","api_set_rarity":"Common","api_set_price":"0.98"},
        {"api_id":55773067,"api_name":"Drop Off","api_set_name":"Legacy of Darkness","api_set_code":"LOD-097","api_set_rarity":"Super Rare","api_set_price":"5.5"},
        {"api_id":42647539,"api_name":"Ryu-Kishin Clown","api_set_name":"Legacy of Darkness","api_set_code":"LOD-007","api_set_rarity":"Common","api_set_price":"1.03"},
        {"api_id":88132637,"api_name":"Twin-Headed Wolf","api_set_name":"Legacy of Darkness","api_set_code":"LOD-008","api_set_rarity":"Common","api_set_price":"0.99"},
        {"api_id":14531242,"api_name":"Opticlops","api_set_name":"Legacy of Darkness","api_set_code":"LOD-009","api_set_rarity":"Rare","api_set_price":"1.07"},
        {"api_id":41925941,"api_name":"Bark of Dark Ruler","api_set_name":"Legacy of Darkness","api_set_code":"LOD-010","api_set_rarity":"Common","api_set_price":"0.98"},
        {"api_id":77910045,"api_name":"Fatal Abacus","api_set_name":"Legacy of Darkness","api_set_code":"LOD-011","api_set_rarity":"Rare","api_set_price":"1.09"},
        {"api_id":14318794,"api_name":"Life Absorbing Machine","api_set_name":"Legacy of Darkness","api_set_code":"LOD-012","api_set_rarity":"Common","api_set_price":"1.55"},
        {"api_id":40703393,"api_name":"The Puppet Magic of Dark Ruler","api_set_name":"Legacy of Darkness","api_set_code":"LOD-013","api_set_rarity":"Common","api_set_price":"0.98"},
        {"api_id":76297408,"api_name":"Soul Demolition","api_set_name":"Legacy of Darkness","api_set_code":"LOD-014","api_set_rarity":"Common","api_set_price":"0.98"},
        {"api_id":3682106,"api_name":"Double Snare","api_set_name":"Legacy of Darkness","api_set_code":"LOD-015","api_set_rarity":"Common","api_set_price":"0.98"},
        {"api_id":53183600,"api_name":"Blue-Eyes Toon Dragon","api_set_name":"Magic Ruler","api_set_code":"MRL-000","api_set_rarity":"Secret Rare","api_set_price":"264.47"},
        {"api_id":66516792,"api_name":"Serpent Night Dragon","api_set_name":"Magic Ruler","api_set_code":"MRL-103","api_set_rarity":"Secret Rare","api_set_price":"9.27"},
        {"api_id":40619825,"api_name":"Axe of Despair","api_set_name":"Magic Ruler","api_set_code":"MRL-002","api_set_rarity":"Ultra Rare","api_set_price":"5.31"},
        {"api_id":65169794,"api_name":"Black Pendant","api_set_name":"Magic Ruler","api_set_code":"MRL-003","api_set_rarity":"Super Rare","api_set_price":"3.95"},
        {"api_id":38552107,"api_name":"Horn of Light","api_set_name":"Magic Ruler","api_set_code":"MRL-004","api_set_rarity":"Common","api_set_price":"1.1"},
        {"api_id":99597615,"api_name":"Malevolent Nuzzler","api_set_name":"Magic Ruler","api_set_code":"MRL-005","api_set_rarity":"Common","api_set_price":"0.97"},
        {"api_id":18807109,"api_name":"Spellbinding Circle","api_set_name":"Magic Ruler","api_set_code":"MRL-006","api_set_rarity":"Ultra Rare","api_set_price":"10.42"},
        {"api_id":55998462,"api_name":"Metal Fish","api_set_name":"Magic Ruler","api_set_code":"MRL-007","api_set_rarity":"Common","api_set_price":"0.95"},
        {"api_id":11324436,"api_name":"Electric Snake","api_set_name":"Magic Ruler","api_set_code":"MRL-008","api_set_rarity":"Common","api_set_price":"0.97"},
        {"api_id":73081602,"api_name":"Queen Bird","api_set_name":"Magic Ruler","api_set_code":"MRL-009","api_set_rarity":"Common","api_set_price":"0.98"},
        {"api_id":95174353,"api_name":"Ameba","api_set_name":"Magic Ruler","api_set_code":"MRL-010","api_set_rarity":"Rare","api_set_price":"1.21"},
        {"api_id":38033126,"api_name":"Dark Magician Girl","api_set_name":"Magician's Force","api_set_code":"MFC-000","api_set_rarity":"Secret Rare","api_set_price":"1074.94"},
        {"api_id":12143771,"api_name":"People Running About","api_set_name":"Magician's Force","api_set_code":"MFC-001","api_set_rarity":"Common","api_set_price":"1"},
        {"api_id":58538870,"api_name":"Oppressed People","api_set_name":"Magician's Force","api_set_code":"MFC-002","api_set_rarity":"Common","api_set_price":"2.81"},
        {"api_id":85936485,"api_name":"United Resistance","api_set_name":"Magician's Force","api_set_code":"MFC-003","api_set_rarity":"Common","api_set_price":"0.97"},
        {"api_id":62651957,"api_name":"X-Head Cannon","api_set_name":"Magician's Force","api_set_code":"MFC-004","api_set_rarity":"Super Rare","api_set_price":"3.27"},
        {"api_id":65622692,"api_name":"Y-Dragon Head","api_set_name":"Magician's Force","api_set_code":"MFC-005","api_set_rarity":"Super Rare","api_set_price":"4.04"},
        {"api_id":64500000,"api_name":"Z-Metal Tank","api_set_name":"Magician's Force","api_set_code":"MFC-006","api_set_rarity":"Super Rare","api_set_price":"3.41"},
        {"api_id":11321183,"api_name":"Dark Blade","api_set_name":"Magician's Force","api_set_code":"MFC-007","api_set_rarity":"Rare","api_set_price":"1.26"},
        {"api_id":47415292,"api_name":"Pitch-Dark Dragon","api_set_name":"Magician's Force","api_set_code":"MFC-008","api_set_rarity":"Common","api_set_price":"1.26"},
        {"api_id":84814897,"api_name":"Kiryu","api_set_name":"Magician's Force","api_set_code":"MFC-009","api_set_rarity":"Common","api_set_price":"1.87"},
        {"api_id":10209545,"api_name":"Decayed Commander","api_set_name":"Magician's Force","api_set_code":"MFC-010","api_set_rarity":"Common","api_set_price":"0.97"},
        {"api_id":47693640,"api_name":"Zombie Tiger","api_set_name":"Magician's Force","api_set_code":"MFC-011","api_set_rarity":"Common","api_set_price":"1.05"},
        {"api_id":73698349,"api_name":"Giant Orc","api_set_name":"Magician's Force","api_set_code":"MFC-012","api_set_rarity":"Common","api_set_price":"1.22"},
        {"api_id":25833572,"api_name":"Gate Guardian","api_set_name":"Metal Raapi_iders","api_set_code":"MRD-000","api_set_rarity":"Secret Rare","api_set_price":"41.98"},
        {"api_id":41392891,"api_name":"Feral Imp","api_set_name":"Metal Raapi_iders","api_set_code":"MRD-001","api_set_rarity":"Common","api_set_price":"1.19"},
        {"api_id":87796900,"api_name":"Winged Dragon, Guardian of the Fortress #1","api_set_name":"Metal Raapi_iders","api_set_code":"MRD-002","api_set_rarity":"Common","api_set_price":"1.04"},
        {"api_id":70781055,"api_name":"Summoned Skull","api_set_name":"Metal Raapi_iders","api_set_code":"MRD-003","api_set_rarity":"Ultra Rare","api_set_price":"22.07"},
        {"api_id":68846917,"api_name":"Rock Ogre Grotto #1","api_set_name":"Metal Raapi_iders","api_set_code":"MRD-004","api_set_rarity":"Common","api_set_price":"1.04"},
        {"api_id":15480588,"api_name":"Armored Lizard","api_set_name":"Metal Raapi_iders","api_set_code":"MRD-005","api_set_rarity":"Common","api_set_price":"0.97"},
        {"api_id":88979991,"api_name":"Killer Needle","api_set_name":"Metal Raapi_iders","api_set_code":"MRD-006","api_set_rarity":"Common","api_set_price":"2.51"},
        {"api_id":87756343,"api_name":"Larvae Moth","api_set_name":"Metal Raapi_iders","api_set_code":"MRD-007","api_set_rarity":"Common","api_set_price":"1.23"},
        {"api_id":76812113,"api_name":"Harpie Lady","api_set_name":"Metal Raapi_iders","api_set_code":"MRD-008","api_set_rarity":"Common","api_set_price":"16.52"},
        {"api_id":12206212,"api_name":"Harpie Lady Sisters","api_set_name":"Metal Raapi_iders","api_set_code":"MRD-009","api_set_rarity":"Super Rare","api_set_price":"3.82"},
        {"api_id":1184620,"api_name":"Kojikocy","api_set_name":"Metal Raapi_iders","api_set_code":"MRD-010","api_set_rarity":"Common","api_set_price":"1"},
        {"api_id":40240595,"api_name":"Cocoon of Evolution","api_set_name":"Metal Raapi_iders","api_set_code":"MRD-011","api_set_rarity":"Super Short Print","api_set_price":"1.63"},
        {"api_id":67494157,"api_name":"Crawling Dragon","api_set_name":"Metal Raapi_iders","api_set_code":"MRD-012","api_set_rarity":"Common","api_set_price":"1.17"},
        {"api_id":77585514,"api_name":"Jinzo","api_set_name":"Pharaoh's Servant","api_set_code":"PSV-000","api_set_rarity":"Secret Rare","api_set_price":"62.69"},
        {"api_id":90908427,"api_name":"Steel Ogre Grotto #2","api_set_name":"Pharaoh's Servant","api_set_code":"PSV-001","api_set_rarity":"Common","api_set_price":"0.92"},
        {"api_id":78423643,"api_name":"Three-Headed Geedo","api_set_name":"Pharaoh's Servant","api_set_code":"PSV-002","api_set_rarity":"Common","api_set_price":"0.94"},
        {"api_id":27911550,"api_name":"Parasite Paracapi_ide","api_set_name":"Pharaoh's Servant","api_set_code":"PSV-003","api_set_rarity":"Super Rare","api_set_price":"5.38"},
        {"api_id":86198326,"api_name":"7 Completed","api_set_name":"Pharaoh's Servant","api_set_code":"PSV-004","api_set_rarity":"Common","api_set_price":"0.98"},
        {"api_id":49587034,"api_name":"Lightforce Sword","api_set_name":"Pharaoh's Servant","api_set_code":"PSV-005","api_set_rarity":"Rare","api_set_price":"1"},
        {"api_id":1248895,"api_name":"Chain Destruction","api_set_name":"Pharaoh's Servant","api_set_code":"PSV-006","api_set_rarity":"Ultra Rare","api_set_price":"2.36"},
        {"api_id":35316708,"api_name":"Time Seal","api_set_name":"Pharaoh's Servant","api_set_code":"PSV-007","api_set_rarity":"Short Print","api_set_price":"2.75"},
        {"api_id":61705417,"api_name":"Graverobber","api_set_name":"Pharaoh's Servant","api_set_code":"PSV-008","api_set_rarity":"Super Rare","api_set_price":"6.81"},
        {"api_id":98299011,"api_name":"Gift of the Mystical Elf","api_set_name":"Pharaoh's Servant","api_set_code":"PSV-009","api_set_rarity":"Short Print","api_set_price":"1.19"},
        {"api_id":34694160,"api_name":"The Eye of Truth","api_set_name":"Pharaoh's Servant","api_set_code":"PSV-010","api_set_rarity":"Short Print","api_set_price":"0.97"},
        {"api_id":60082869,"api_name":"Dust Tornado","api_set_name":"Pharaoh's Servant","api_set_code":"PSV-011","api_set_rarity":"Super Rare","api_set_price":"3.57"},
        {"api_id":97077563,"api_name":"Call of the Haunted","api_set_name":"Pharaoh's Servant","api_set_code":"PSV-012","api_set_rarity":"Ultra Rare","api_set_price":"13.13"},
        {"api_id":23471572,"api_name":"Solomon's Lawbook","api_set_name":"Pharaoh's Servant","api_set_code":"PSV-013","api_set_rarity":"Common","api_set_price":"0.96"},
        {"api_id":60866277,"api_name":"Earthshaker","api_set_name":"Pharaoh's Servant","api_set_code":"PSV-014","api_set_rarity":"Common","api_set_price":"0.9"},
        {"api_id":96355986,"api_name":"Enchanted Javelin","api_set_name":"Pharaoh's Servant","api_set_code":"PSV-015","api_set_rarity":"Common","api_set_price":"0.97"},
        {"api_id":83555667,"api_name":"Ring of Destruction","api_set_name":"Pharaonic Guardian","api_set_code":"PGD-000","api_set_rarity":"Secret Rare","api_set_price":"22.76"},
        {"api_id":17192817,"api_name":"Molten Behemoth","api_set_name":"Pharaonic Guardian","api_set_code":"PGD-001","api_set_rarity":"Common","api_set_price":"0.95"},
        {"api_id":4035199,"api_name":"Shapesnatch","api_set_name":"Pharaonic Guardian","api_set_code":"PGD-002","api_set_rarity":"Common","api_set_price":"1.5"},
        {"api_id":31242786,"api_name":"Souleater","api_set_name":"Pharaonic Guardian","api_set_code":"PGD-003","api_set_rarity":"Common","api_set_price":"0.98"},
        {"api_id":83986578,"api_name":"King Tiger Wanghu","api_set_name":"Pharaonic Guardian","api_set_code":"PGD-004","api_set_rarity":"Rare","api_set_price":"7.74"},
        {"api_id":45547649,"api_name":"Birdface","api_set_name":"Pharaonic Guardian","api_set_code":"PGD-005","api_set_rarity":"Common","api_set_price":"2.09"},
        {"api_id":82642348,"api_name":"Kryuel","api_set_name":"Pharaonic Guardian","api_set_code":"PGD-006","api_set_rarity":"Common","api_set_price":"1.07"},
        {"api_id":42364374,"api_name":"Arsenal Bug","api_set_name":"Pharaonic Guardian","api_set_code":"PGD-007","api_set_rarity":"Common","api_set_price":"0.98"},
        {"api_id":17214465,"api_name":"Maapi_iden of the Aqua","api_set_name":"Pharaonic Guardian","api_set_code":"PGD-008","api_set_rarity":"Short Print","api_set_price":"4.38"},
        {"api_id":5257687,"api_name":"Jowls of Dark Demise","api_set_name":"Pharaonic Guardian","api_set_code":"PGD-009","api_set_rarity":"Rare","api_set_price":"1.36"},
        {"api_id":44913552,"api_name":"Timeater","api_set_name":"Pharaonic Guardian","api_set_code":"PGD-010","api_set_rarity":"Common","api_set_price":"1.08"},
        {"api_id":70307656,"api_name":"Mucus Yolk","api_set_name":"Pharaonic Guardian","api_set_code":"PGD-011","api_set_rarity":"Common","api_set_price":"1.15"},
        {"api_id":2792265,"api_name":"Servant of Catabolism","api_set_name":"Pharaonic Guardian","api_set_code":"PGD-012","api_set_rarity":"Common","api_set_price":"0.97"},
        {"api_id":75285069,"api_name":"Moisture Creature","api_set_name":"Pharaonic Guardian","api_set_code":"PGD-013","api_set_rarity":"Rare","api_set_price":"1.15"},
        {"api_id":80233946,"api_name":"Gora Turtle","api_set_name":"Pharaonic Guardian","api_set_code":"PGD-014","api_set_rarity":"Rare","api_set_price":"1.1"},
        {"api_id":16222645,"api_name":"Sasuke Samurai","api_set_name":"Pharaonic Guardian","api_set_code":"PGD-015","api_set_rarity":"Super Rare","api_set_price":"4.48"},
        {"api_id":43716289,"api_name":"Poison Mummy","api_set_name":"Pharaonic Guardian","api_set_code":"PGD-016","api_set_rarity":"Common","api_set_price":"1.98"},
        {"api_id":89111398,"api_name":"Dark Dust Spirit","api_set_name":"Pharaonic Guardian","api_set_code":"PGD-017","api_set_rarity":"Short Print","api_set_price":"3.03"},
        {"api_id":42994702,"api_name":"Wandering Mummy","api_set_name":"Pharaonic Guardian","api_set_code":"PGD-019","api_set_rarity":"Rare","api_set_price":"1.15"},
        {"api_id":88989706,"api_name":"Great Dezard","api_set_name":"Pharaonic Guardian","api_set_code":"PGD-020","api_set_rarity":"Ultra Rare","api_set_price":"4.42"},
    ]

    for i in range(len(card_seeds)):
        temp = Card(
        api_id = card_seeds[i]["api_id"],
        api_name = card_seeds[i]["api_name"],
        api_set_name= card_seeds[i]["api_set_name"],
        api_set_code = card_seeds[i]["api_set_code"],
        api_set_rarity =card_seeds[i]["api_set_rarity"],
        api_set_price =card_seeds[i]["api_set_price"])
        db.session.add(temp)
    db.session.commit()

# Uses a raw SQL query to TRUNCATE the users table.
# SQLAlchemy doesn't have a built in function to do this
# TRUNCATE Removes all the data from the table, and resets
# the auto incrementing primary key

def undo_cards():
    db.session.execute('TRUNCATE cards RESTART IDENTITY CASCADE;')
    db.session.commit()
