"""empty message

Revision ID: d421543d7aeb
Revises: 14b006c98d3b
Create Date: 2021-08-05 22:15:36.122274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd421543d7aeb'
down_revision = '14b006c98d3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'admin',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('users', 'f_name')
    op.drop_column('users', 'l_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('l_name', sa.VARCHAR(length=40), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('f_name', sa.VARCHAR(length=40), autoincrement=False, nullable=False))
    op.alter_column('users', 'admin',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
